name: flutter_audio_recorder4_example
description: "Demonstrates how to use the flutter_audio_recorder4 plugin."

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.1  #TODO - CHRIS - update to  2.1.1
  file: ^7.0.0
  audioplayers: ^0.19.0   #TODO - CHRIS - update to 5.2.0
  cupertino_icons: ^1.0.2

  flutter_audio_recorder4:
    # When depending on this package from a real application you should use:
    #   flutter_audio_recorder4: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true